# Generated by Django 2.1.5 on 2019-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contents_link_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='link_site',
            field=models.CharField(max_length=10000),
        ),
    ]
