# Generated by Django 2.1.5 on 2019-03-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190308_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='link_site',
            field=models.TextField(),
        ),
    ]
