# Generated by Django 2.1.5 on 2019-03-09 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
