# Generated by Django 2.1.5 on 2019-03-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contents_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
