# Generated by Django 2.1.5 on 2019-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190310_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='upload_image_to',
            field=models.FileField(blank=True, upload_to='media/blog/images'),
        ),
        migrations.AddField(
            model_name='contents',
            name='upload_video_to',
            field=models.FileField(blank=True, upload_to='media/polls/videos'),
        ),
    ]
