# Generated by Django 2.1.5 on 2019-03-16 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190312_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='toppings',
            field=models.CharField(choices=[('a', 'Anchovies'), ('b', 'Black olives'), ('p', 'Pepperoni'), ('m', 'Mozzarella')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
