# Generated by Django 2.1.5 on 2019-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contents_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='toppings',
            field=models.CharField(choices=[('cu', 'Culture'), ('bu', 'Business'), ('de', 'Design'), ('he', 'Health'), ('in', 'India'), ('op', 'Opinion'), ('po', 'Politics'), ('sc', 'Science'), ('st', 'Style'), ('te', 'Technology'), ('tr', 'Travel'), ('wo', 'World')], max_length=10),
        ),
    ]
